//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCIV.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SCIVEntities : DbContext
    {
        public SCIVEntities()
            : base("name=SCIVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Tab_Bitacora_Movimientos> Tab_Bitacora_Movimientos { get; set; }
        public DbSet<Tab_Bitacora_Sesiones> Tab_Bitacora_Sesiones { get; set; }
        public DbSet<Tab_Empresa> Tab_Empresa { get; set; }
        public DbSet<Tab_Lista_Ventas> Tab_Lista_Ventas { get; set; }
        public DbSet<Tab_Lista_Ventas_Detalles> Tab_Lista_Ventas_Detalles { get; set; }
        public DbSet<Tab_Perfiles> Tab_Perfiles { get; set; }
        public DbSet<Tab_Permisos> Tab_Permisos { get; set; }
        public DbSet<Tab_Productos> Tab_Productos { get; set; }
        public DbSet<Tab_Telefono> Tab_Telefono { get; set; }
        public DbSet<Tab_Usuarios> Tab_Usuarios { get; set; }
        public DbSet<Tab_Venta_Detalle> Tab_Venta_Detalle { get; set; }
    }
}
