//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCIV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tab_Telefono
    {
        public long Cedula_Juridica { get; set; }
        public int Telefono { get; set; }
        public string Contacto { get; set; }
    
        public virtual Tab_Empresa Tab_Empresa { get; set; }
    }
}
