//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCIV.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tab_Usuarios
    {
        public Tab_Usuarios()
        {
            this.Tab_Bitacora_Movimientos = new HashSet<Tab_Bitacora_Movimientos>();
            this.Tab_Bitacora_Sesiones = new HashSet<Tab_Bitacora_Sesiones>();
            this.Tab_Lista_Ventas = new HashSet<Tab_Lista_Ventas>();
            this.Tab_Venta_Detalle = new HashSet<Tab_Venta_Detalle>();
        }

        [Required]
        //[StringLength(10, ErrorMessage = "El nombre es muy largo.")]
        public int Cedula { get; set; }
        [Required]
        [MinLength(8,ErrorMessage ="El nombre de usuario es muy corto.")]
        [StringLength(25, ErrorMessage = "El nombre de usuario es muy largo.")]
        public string NickName { get; set; }
        // [Required(ErrorMessage = "Debe especificar el nombre.")]
        [StringLength(30, ErrorMessage = "El nombre es muy largo.")]
        [Required]
        public string Nombre { get; set; }
        // [Required(ErrorMessage = "Debe especificar el primer apellido.")]
        [StringLength(30, ErrorMessage = "El primer apellido es muy largo.")]
        [Required]
        public string Apellido1 { get; set; }
        //[Required(ErrorMessage = "Debe especificar el segundo apellido.")]
        [StringLength(30, ErrorMessage = "El segundo apellido es muy largo.")]
        [Required]
        public string Apellido2 { get; set; }
        [Required]
        [DataType(DataType.Password)]
        [MinLength(8, ErrorMessage = "La contraseña es muy corta.")]
        // [StringLength(16, ErrorMessage ="La contraseña no contiene la cantidad de caracteres correcta",MinimumLength = 8)]
        public string Contrasena { get; set; }
        public string Genero { get; set; }
        public int Id_Perfil { get; set; }
    
        public virtual ICollection<Tab_Bitacora_Movimientos> Tab_Bitacora_Movimientos { get; set; }
        public virtual ICollection<Tab_Bitacora_Sesiones> Tab_Bitacora_Sesiones { get; set; }
        public virtual ICollection<Tab_Lista_Ventas> Tab_Lista_Ventas { get; set; }
        public virtual Tab_Perfiles Tab_Perfiles { get; set; }
        public virtual ICollection<Tab_Venta_Detalle> Tab_Venta_Detalle { get; set; }
    }
}
