//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCIV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tab_Empresa
    {
        public Tab_Empresa()
        {
            this.Tab_Lista_Ventas = new HashSet<Tab_Lista_Ventas>();
            this.Tab_Telefono = new HashSet<Tab_Telefono>();
        }
    
        public long Cedula_Juridica { get; set; }
        public string Nombre_Empresa { get; set; }
        public int Telefono { get; set; }
        public string Correo { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<Tab_Lista_Ventas> Tab_Lista_Ventas { get; set; }
        public virtual ICollection<Tab_Telefono> Tab_Telefono { get; set; }
    }
}
