//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCIV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tab_Productos
    {
        public Tab_Productos()
        {
            this.Tab_Lista_Ventas_Detalles = new HashSet<Tab_Lista_Ventas_Detalles>();
            this.Tab_Venta_Detalle = new HashSet<Tab_Venta_Detalle>();
        }
    
        public int Codigo { get; set; }
        public string Nombre_producto { get; set; }
        public string Descripcion_producto { get; set; }
        public double Precio_Costo { get; set; }
        public Nullable<int> Cantidad_Unidades { get; set; }
    
        public virtual ICollection<Tab_Lista_Ventas_Detalles> Tab_Lista_Ventas_Detalles { get; set; }
        public virtual ICollection<Tab_Venta_Detalle> Tab_Venta_Detalle { get; set; }
    }
}
