//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCIV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tab_Permisos
    {
        public int Id_Perfil { get; set; }
        public int Modulo { get; set; }
        public string Agregar { get; set; }
        public string Modificar { get; set; }
        public string Consultar { get; set; }
        public string Eliminar { get; set; }
    
        public virtual Tab_Perfiles Tab_Perfiles { get; set; }
    }
}
