//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCIV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tab_Bitacora_Movimientos
    {
        public System.DateTime Fecha_Hora { get; set; }
        public int Id_Movimiento { get; set; }
        public string Tipo_Movimiento { get; set; }
        public string Modulo_Afectado { get; set; }
        public string NickName { get; set; }
    
        public virtual Tab_Usuarios Tab_Usuarios { get; set; }
    }
}
