//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCIV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tab_Lista_Ventas_Detalles
    {
        public int Id_Lista { get; set; }
        public int Codigo_Producto { get; set; }
        public int Paquetes { get; set; }
        public int Cantidad_Total { get; set; }
        public Nullable<int> Cantidad_Actual { get; set; }
        public double Precio_Costo { get; set; }
        public double Porcentaje_Ganancia { get; set; }
    
        public virtual Tab_Lista_Ventas Tab_Lista_Ventas { get; set; }
        public virtual Tab_Productos Tab_Productos { get; set; }
    }
}
