//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCIV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tab_Lista_Ventas
    {
        public Tab_Lista_Ventas()
        {
            this.Tab_Lista_Ventas_Detalles = new HashSet<Tab_Lista_Ventas_Detalles>();
        }
    
        public long Cedula_Empresa { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Id_Lista { get; set; }
        public string NickName_Creador { get; set; }
        public string Nota_Adicional { get; set; }
    
        public virtual Tab_Empresa Tab_Empresa { get; set; }
        public virtual ICollection<Tab_Lista_Ventas_Detalles> Tab_Lista_Ventas_Detalles { get; set; }
        public virtual Tab_Usuarios Tab_Usuarios { get; set; }
    }
}
