//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCIV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tab_Perfiles
    {
        public Tab_Perfiles()
        {
            this.Tab_Permisos = new HashSet<Tab_Permisos>();
            this.Tab_Usuarios = new HashSet<Tab_Usuarios>();
        }
    
        public int Id_Perfil { get; set; }
        public string Nombre_Perfil { get; set; }
    
        public virtual ICollection<Tab_Permisos> Tab_Permisos { get; set; }
        public virtual ICollection<Tab_Usuarios> Tab_Usuarios { get; set; }
    }
}
